services:
  - type: web
    name: fodmap-backend
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        value: jdbc:mysql://your-mysql-host:3306/your-database-name
      - key: DB_USERNAME
        value: your-username
      - key: DB_PASSWORD
        value: your-password
    plan: free  # or the desired plan
    region: frankfurt  # or the preferred region
    runtime: java21
