services:
  - type: web
    name: fodmap-backend
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        value: jdbc:mysql://localhost:9000/foodmap
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: admin
    plan: free  # or the desired plan
    region: frankfurt  # or the preferred region
    runtime: java21
