# Etapa 1: Construcción de la aplicación Java
FROM eclipse-temurin:21-jdk AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo pom.xml y descargar las dependencias necesarias
COPY pom.xml .

# Descargar las dependencias (caché de capas)
RUN ./mvnw dependency:go-offline -B

# Copiar el resto del código de la aplicación
COPY src ./src

# Compilar la aplicación
RUN ./mvnw clean install -DskipTests

# Etapa 2: Generar imagen liviana para ejecución
FROM eclipse-temurin:21-jre-alpine

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el JAR generado desde la etapa de construcción
COPY --from=build /app/target/*.jar app.jar

# Exponer el puerto en el que correrá la aplicación
EXPOSE 9898

# Comando para ejecutar la aplicación
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
