# Etapa 1: Construcción
FROM node:18 AS build

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar package.json y package-lock.json al directorio de trabajo
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto del código de la aplicación al directorio de trabajo
COPY . .

# Construir la aplicación
RUN npm run build

# Etapa 2: Servidor NGINX
FROM nginx:stable-alpine

# Copiar los archivos de construcción desde la etapa 1 al directorio de NGINX
COPY --from=build /app/build /usr/share/nginx/html

# Copiar el archivo de configuración de NGINX
COPY nginx.conf /etc/nginx/nginx.conf

# Exponer el puerto en el que NGINX correrá
EXPOSE 80

# Comando para ejecutar NGINX
CMD ["nginx", "-g", "daemon off;"]
