services:
  - type: web
    name: fodmap-backend
    env: java
    buildCommand: mvn clean install
    startCommand: java -jar target/*.jar
    envVars:
      - key: DB_URL
        value: postgresql://ortizzxz:B6xSPnPvRVmXVvaszYayMgqU9y6oonkW@dpg-cqvneprtq21c7384jvjg-a/fodmap
      - key: DB_USERNAME
        value: ortizzxz
      - key: DB_PASSWORD
        value: B6xSPnPvRVmXVvaszYayMgqU9y6oonkW
    plan: free  # or the desired plan
    region: frankfurt  # or the preferred region
    runtime: java21
    rootDir: ./backend/fodmap-backend  # This is the key line to fix the directory issue
